### ISSUE TITLE
Improve development guide

### ISSUE THREAD

**Issue by simonsan** [rustic-rs/dev-docs#1]
Currently, this is being empty: https://github.com/rustic-rs/rustic/blob/main/docs/dev/development_guide.md

As a starter, we should explain the following things:

- [x] how to use `just` for common commands (#820) 
- [x] `cargo xtask` for coverage reports and installing needed dependencies (#820)
- [ ] setting up an IDE (can help with `VSCodium`) for Rust development
- [ ] link to ARCHITECTURE.md (#757) when ready, so devs can get a fast grip to what is where
- [ ] tbc
